sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hoOzYAbhRaBbrwfGl4YmBfw+901rzKLO3+Nm0XL8qBcZ2wyO6eC46qW5D64bepYCBMq/1M8xlnjo3kxDo4L1Dga2P5unE4i1TQdWL3O9Cr8U2/4n725tAfKVaHirTPF6HEbXhNimyQ3PtqQwkeTCoDN9TVZ7T4C/k+BmIibIuyACnhZZlMpSJXarMzOHFidWNSJgvegTjvoAOi3GoDkxJgwLQKsmaLQSqVxeJGHRsPUazRRY/37CZgpQVenHxL/YttWqzEfUthBT9XyR+Po00tx1cATxhRtGEePBAh5MrBxPMyIE5iePyk7O3LGfbaWEAk5pcj5VzloVxs/bVVBahOj4v1vpVOOzlmrMZgJdDuHQop40m3QmIe1MAeg5xOMWmgUVB4mJtxkPA/UaUZ3kNeNq0qqH2q/F38d8yyrT6J/4UWYUgH2Bt5bz9X+ugSe9PTZ4Z+zzu+JA5gP8B9OEv0RS8MtQkZtZ7gJEoysaMzo4nI9UzlG48aSF5Iahq9gZI6kT9+e5HWIJVynOYLVzIGsJ37iG01KyGcY3hMnzJV0+PeH6uCTKb1z3aLioWj56hKR5nWKWlU7mPtwiLRPgm11voAf19/80z/z9f3pvpl+8WfeOb22CWWahWYS7R5ofMoeZ9XJZcPcsge1Y1UUtSrv+0Fd1o8V9vT7tZoxErrI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Some-Causes-of-the-Prevailing-Discontent_3113
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy